### ISSUE TITLE
토픽과 액션 통신

### ISSUE THREAD

**Issue by wayexists02** [wayexists02/hanyang-erica-robot-programming#11]
토픽 통신은 퍼블리셔가 아무나 퍼가라 하는 식으로 메시지를 뿌리는 것이라서, 서브스크라이버로부터 피드백을 받기가 힘듭니다. 굳이 받으려면 피드백용 토픽을 뚫어야 하는데, 중구난방 되어 버리므로, 서비스와 액션을 고려해야 할 것 같습니다. 하지만, 서비스 통신은 동기적 통신으로, 서비스 요청자는 서비스 결과를 받기 전까지 블록되어 아무것도 하지 못하므로, 액션이 무난해 보입니다(지금 코드 구조가 비동기를 가정하고 구성했기 때문에 서비스를 사용하면 예기치 못한 에러 발생 가능성이 있습니다).

굳이 젤 어려운 액션 통신을 선택한 점 양해 부탁드립니다..ㅠ

**Comment by tutor0613** [comment]
ㅠㅠㅠㅠㅠㅠ

**Comment by PinkWink** [comment]
아니에요. 액션 방식을 선택한 것은 좋아보입니다. 서비스보다는 나을거고, 상태의 확인을 위해서 필요해 보입니다. 좋은 판단이라고 생각합니다.

**Comment by wayexists02** [comment]
액션 통신으로 하다보니, 브로드캐스팅 기능이 더 필요한 듯 해서 일단 다시 토픽으로 롤백했습니다~ㅋㅋ
