### ISSUE TITLE
드론과의 통신 인터페이스

### ISSUE THREAD

**Issue by wayexists02** [wayexists02/hanyang-erica-robot-programming#5]
drone_message 패키지에 있는 메시지를 통해서 드론과 통신하면 된다.
DroneCommand 형식의 메시지는 "codrone_cmd"라는 이름의 토픽으로 명령 보내주면 됨.
DroneInfo 형식으로 메시지가 "codrone_info"라는 이름의 토픽으로 오는데, 이것으로 정보 조회하면 됨.

테스트 필요

**Comment by tutor0613** [comment]
멋있어용..........

**Comment by wayexists02** [comment]
정상작동 확인

최종적으로 이미지만 사용하기에,
정보조회는 필요없어서 "codrone_info" 토픽은 뺐음.
